name:                ledgersort
version:             1.0.0.0
github:              "gregorias/ledgersort"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "gmilka91@gmail.com"
copyright:           "2020 Grzegorz Milka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ledgersort#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - time
  - text
  - megaparsec

executables:
  ledgersort:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ledgersort
    - text

tests:
  ledgersort-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations-pretty-diff
    - ledgersort
    - text
    - time
